=== Lucid-Studios/Holographic-Image-Tool/Hdt.Schemas/Schemas/oan.hopng_trust_envelope.v0.1.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "oan.hopng_trust_envelope.v0.1.0.json",
  "title": "HOPNG Trust Envelope",
  "type": "object",
  "required": [
    "schema",
    "schemaVersion",
    "artifactId",
    "signer",
    "keyId",
    "issuedUtc",
    "publicKey",
    "signingScope"
  ],
  "properties": {
    "schema": { "const": "oan.hopng_trust_envelope" },
    "schemaVersion": { "const": "0.1.0" },
    "artifactId": { "type": "string" },
    "signer": { "type": "string" },
    "keyId": { "type": "string" },
    "issuedUtc": { "type": "string", "format": "date-time" },
    "publicKey": { "type": "string" },
    "signingScope": {
      "type": "array",
      "items": { "type": "string" }
    },
    "signatureFile": { "type": "string" }
  }
}

=== Lucid-Studios/Holographic-Image-Tool/examples/phase3-divergent-peer.trust-envelope.json
{"artifactId":"f196120c-0fed-4d44-944c-0da60949710a","issuedUtc":"2026-03-30T07:50:29.6923219\u002B00:00","keyId":"local-dev-key","publicKey":"pJ6/Iyh2cVXIryVPeIoAmcYShi5nYw4mEtz/HvK79TE=","schema":"oan.hopng_trust_envelope","schemaVersion":"0.1.0","signatureFile":"phase3-divergent-peer.signature.json","signer":"Rober","signingScope":["phase3-divergent-peer.hopng.json","phase3-divergent-peer.hash.json"]}

=== Lucid-Studios/Holographic-Image-Tool/examples/phase1-sample.trust-envelope.json
{"artifactId":"a407d8a5-18eb-4142-947a-4eb110f86bd1","issuedUtc":"2026-03-05T23:13:38.8875642\u002B00:00","keyId":"example-key","publicKey":"onnDApN1MFbBpLigHYHj7WIkKOte9xdouXVqoQmflzE=","schema":"oan.hopng_trust_envelope","schemaVersion":"0.1.0","signatureFile":"phase1-sample.signature.json","signer":"Local Tester","signingScope":["phase1-sample.hopng.json","phase1-sample.hash.json"]}

=== Lucid-Studios/Holographic-Image-Tool/examples/phase4-perspectival-peer.trust-envelope.json
{"artifactId":"71ee9640-daa7-4abd-8980-83bc53607f14","issuedUtc":"2026-03-30T17:13:52.5609169\u002B00:00","keyId":"phase4-reference-key","publicKey":"u9LmpBGxkIrlZAG03z6VC6FZG0f7I3xmZGW6LfG3GBQ=","schema":"oan.hopng_trust_envelope","schemaVersion":"0.1.0","signatureFile":"phase4-perspectival-peer.signature.json","signer":"Reference Builder","signingScope":["phase4-perspectival-peer.hopng.json","phase4-perspectival-peer.hash.json"]}

=== Lucid-Studios/Holographic-Image-Tool/examples/phase3-incompatible-basis.trust-envelope.json
{"artifactId":"a543ba2e-9cc4-40aa-a2be-f6215f33c714","issuedUtc":"2026-03-30T07:33:43.2194102\u002B00:00","keyId":"dev-key","publicKey":"QTOmmxZ4E11/dBBR8XejmPjrZ3ayLHlb0mkoS3nt8pU=","schema":"oan.hopng_trust_envelope","schemaVersion":"0.1.0","signatureFile":"phase3-incompatible-basis.signature.json","signer":"Local Tester","signingScope":["phase3-incompatible-basis.hopng.json","phase3-incompatible-basis.hash.json"]}
